### ISSUE TITLE
library for accessing projects and examples

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/client-auth#1]
we should have a similar library to this for accessing other netsblox APIs like the ones used to get the projects and examples

**Comment by brollb** [comment]
We should probably just use thrift or grpc if we are going to be adding more programmatic access to the netsblox API. Then we wouldn't have to manually write these clients and would automatically support a ton of languages.

**Comment by brollb** [comment]
Addressed as of 828a201f5804646be3275784e6a833862b36dc7d
